language: ruby

bundler_args: "--without production development mac_test"

rvm:
  - 2.0.0

env:
  - DB=postgres

before_script:
  - "cp config/database.travis.$DB.yml config/database.yml"
  - "psql -c 'create database avoin_ministerio_test;' -U postgres"

script: "RAILS_ENV=test bundle exec rake db:migrate spec"

notifications:
  email: travis-notifications@avoinministerio.fi
